---
# tasks file for jenkins
- name: Check java version
  shell: java -version 2>&1 | awk '/version/{print $NF}'
  register: java_version

- name: Add jenkins yum repository
  yum_repository:
    name: jenkins
    description: Jenkins YUM repo
    baseurl: https://pkg.jenkins.io/redhat-stable/
    state: present

- name: Add Jenkins yum repository
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: Install jenkins
  yum:
    name: jenkins
    state: present
- name: Start jenkins
  service:
    name: jenkins
    state: started